### PR TITLE
Introducing folders

### PR DESCRIPTION
**Pull request by jo-mueller**
Hi @haesleinhuepf @zoccoler ,

I added the notebook for the file operations and organized the other notebooks in folders so it stays tidy as the list of notebooks grows longer.

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Awesome, thanks Johannes @jo-mueller ! Just curious, will this folder change break the links in the emails we sent in the past?

**Comment by jo-mueller** [comment]
@haesleinhuepf good point, absolutely. I added copies of the notebooks at their former locations so that the links from the last mail work.

**Comment by haesleinhuepf** [comment]
Awesome, thanks. When would be a good time for merging? Right after the session or before?

**Comment by zoccoler** [comment]
Great! Thanks Johannes @jo-mueller!
I think we should merge after the session.

**Pull request merged**
